<div class="row related-product-container">
  <div class="small-12 column">
    <h2>Related Products</h2>
    <?php // Grid of products generated by the module we haven't decided on yet. ?>


  </div>
</div>
